"""Add User-ApiKey relationship

Revision ID: 8305443076db
Revises: 05d9480cf108
Create Date: 2025-05-25 16:10:39.167947

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8305443076db'
down_revision = '05d9480cf108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
